version: '3'
services:

  node-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: node-app
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
    networks:
      - exchange

  postgres:
    image: "postgres:14.5"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "change-me"
      POSTGRES_PASSWORD: "change-me"
      POSTGRES_DB: "exchange"
    networks:
      - exchange

  cache:
      image: redis:6.2-alpine
      restart: always
      ports:
        - '6379:6379'
      command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
      volumes: 
        - cache:/data
      networks:
      - exchange

  rabbitmq:
    image: "rabbitmq:3.9.10-management-alpine"
    container_name: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=change-me
      - RABBITMQ_DEFAULT_PASS=change-me
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - queue:/var/lib/rabbitmq/
      - queue:/var/log/rabbitmq
    networks:
      - exchange

networks:
  exchange:
    driver: bridge
    
volumes:
  cache:
    driver: local
  queue:
    driver: local